### ISSUE TITLE
Correcciones y comentarios

### ISSUE THREAD

**Issue by DamRCorba** [Adrian-REH/Adrian-REH-TrabajoPractico-Informatica2_TCP#2]
Adrian, la memoria descriptiva esta muy prolija y detallada. No te vuelvas loco con el codigo. Simulalo, utiliza scanf y printf para los cambios de mensajes. Lo ideal es que llegues a noviembre con el tp.

Saludos

**Comment by Adrian-REH** [comment]
> Adrian, la memoria descriptiva esta muy prolija y detallada. No te vuelvas loco con el codigo. Simulalo, utiliza scanf y printf para los cambios de mensajes. Lo ideal es que llegues a noviembre con el tp.
> 
> Saludos

Profesor, imagine el inicio del proyecto de este modo:
 1. Creo dos proyectos que tenga las mismas funciones, con interaccion manual.
 2. los mismos estan enlazados por un archivo de dato.
 3. el archivo de dato guarda el segmento TCP(siempre al finalizar una cominicacion se borra todo lo que hay dentro).
 4. La compilacion de los proyectos:
    - limpia los archivos
    - Inicia con un encabezado(determina el Puerto )
    - Los dos estaran en un bucle LISTEN (revisan el archivo dato vacio para ver si se lleno) y un printf/scanf para iniciar un 
      llenado de datos(por terminal)
    - si uno inicio el llenado entonces el otro lee el archivo prosigiendo al cierre del bucle LISTEN (sigue funcionamiento del TCP).
    

Esta bien el planteo?.
_Es solo la primera parte de la forma de comunicacion, al incio estaba pensando en un solo proyecto que haga el trabajo de las dos maquinas, una interaccion automatica y la otra manual(por terminal)_

**Comment by Adrian-REH** [comment]
> Adrian, la memoria descriptiva esta muy prolija y detallada. No te vuelvas loco con el codigo. Simulalo, utiliza scanf y printf para los cambios de mensajes. Lo ideal es que llegues a noviembre con el tp.
> 
> Saludos

Profesor, imagine el inicio del proyecto de este modo:
 1. Creo dos proyectos que tenga las mismas funciones, con interaccion manual.
 2. los mismos estan enlazados por un archivo de dato.
 3. el archivo de dato guarda el segmento TCP(siempre al finalizar una cominicacion se borra todo lo que hay dentro).
 4. La compilacion de los proyectos:
    - limpia los archivos
    - Inicia con un encabezado(determina el Puerto )
    - Los dos estaran en un bucle LISTEN (revisan el archivo dato vacio para ver si se lleno) y un printf/scanf para iniciar un 
      llenado de datos(por terminal)
    - si uno inicio el llenado entonces el otro lee el archivo prosigiendo al cierre del bucle LISTEN (sigue funcionamiento del TCP).
    

Esta bien el planteo?.
_Es solo la primera parte de la forma de comunicacion, al incio estaba pensando en un solo proyecto que haga el trabajo de las dos maquinas, una interaccion automatica y la otra manual(por terminal)_

**Comment by DamRCorba** [comment]
Si, es correcto.
